export enum ENUM_COMMENT_STATUS_CODE_ERROR {
  COMMENT_NOT_FOUND_ERROR = 5601,
  COMMENT_EXISTS_ERROR = 5602,
  COMMENT_ACCESS_ERROR = 5603,
  COMMENT_TAG_EXIST_ERROR = 5604,
  COMMENT_TAG_NOT_EXIST_ERROR = 5605,
}